
version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          BUNDLER_VERSION: 2.0.2
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: my_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/memoryfootprint
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:12.2
        environment:
          BUNDLER_VERSION: 2.0.2
          POSTGRES_USER: postgres
          POSTGRES_DB: my_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/memoryfootprint
    steps:
      - checkout
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
