
version: 2
jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
          BUNDLER_VERSION: 2.1.4
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_test
    working_directory: ~/memoryfootprint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall -ax bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler -v 2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle --full-index
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
          BUNDLER_VERSION: 2.1.4
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: my_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/memoryfootprint
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall -ax bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler -v 2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle --full-index
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec
      #自動デプロイ
      - add_ssh_keys:
            fingerprints:
              - "38:91:bf:b1:40:6b:06:df:62:dd:b5:86:f1:34:ce:4b"
      - deploy:
             name: Capistrano deploy
             command: |
               if [ "${CIRCLE_BRANCH}" != "master" ]; then
                 exit 0
               fi
               bundle exec cap production deploy

workflows:
  version: 2
  rubocop_rspec:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
